server:
  port: 8022
  servlet:
    context-path: /ps
spring:
  application:
    name: ps
  profiles:
    active: dev
  servlet:
    multipart:
      # 文件上传大小限制为500m
      max-file-size: 500MB
      # 单次请求不得超过1000m
      max-request-size: 1000MB
      # 缓存文件目录。这里要设置绝对路径，且文件夹要存在。
      location: /data/upload-file/temp
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/product_show_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1

#mybatis-plus:
#  global-config:
#    db-config:
#      # ignored: 忽略非空判断，所有字段都可以被更新为 null
#      # not_null: 更新为 null时,忽略更新
#      # not_empty: 字符串不能被更新为 null 或 空，其他类型不能被更新为 null
#      update-strategy: ignored