spring:
  servlet:
    multipart:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/product_show_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password: redismm123
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms

# 静态资源服务路径
file:
  static-root:
  # ffmpeg bin 目录位置
  ffmpeg-bin-dir: ../tool/ffmpeg/ffmpeg-4.4-full_build/bin
  # 转码目录位置
  out-dir: ../data/tmp-video
  # 上传文件缓存目录，文件存储已经迁移到minio-space
  file-space: ../data/upload-file
  # MinIO存储位置
  minio-space: D:/SoftwareData/Docker/MinIO/data

# mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 定时同步点赞计数到数据库
cron:
  1: 0/15 * * * * ?

# MinIO
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin123405
  secret-key: minioadmin123450